
const $=s=>document.querySelector(s), $$=s=>Array.from(document.querySelectorAll(s));
let JOBS=[];
const routes={"/home":()=>show("view-home"),"/jobs":()=>{show("view-jobs");loadJobs();},"/job":()=>{show("view-job");renderJobDetail();},"/resumes":()=>{show("view-resumes");initResumes();},"/employer":()=>show("view-employer"),"/employer/jobs":()=>{show("view-employer-jobs");renderEmployerJobs();},"/admin":()=>{show("view-admin");initAdmin();}};
function show(id){["view-home","view-jobs","view-job","view-resumes","view-employer","view-employer-jobs","view-admin"].forEach(v=>$("#"+v).classList.add("hidden"));$("#"+id).classList.remove("hidden");}
function nav(){const hash=location.hash.replace("#","")||"/home";const base=hash.split("?")[0];(routes[base]||routes["/home"])();}
window.addEventListener("hashchange", nav);
window.addEventListener("load", async ()=>{$("#yr").textContent=new Date().getFullYear(); JOBS = await (await fetch("./data/jobs.json")).json(); nav(); bindGlobalSearch(); });

function jobCard(j){const posted=new Date(j.posted).toLocaleDateString();return `<article class="jobcard"><div class="row spread"><div><div class="row gap vcenter"><h3 style="margin:.1rem 0">${j.title}</h3><span class="badge">${j.company}</span></div><div class="jobmeta"><span>${j.location}</span><span>${j.expMin}-${j.expMax} yrs</span><span>${j.ctc}</span></div><div class="tiny muted">Posted ${posted}</div><div style="margin-top:6px">${j.tags.map(t=>`<span class="tag">${t}</span>`).join("")}</div></div><div class="jobactions"><button class="btn ghost act-detail" data-id="${j.id}">Details</button><button class="btn ghost act-save">Save</button><button class="btn ghost act-share" data-id="${j.id}">Share</button></div></div></article>`;}
function loadJobs(){const kwEl=$("#kw");const params=new URLSearchParams(location.hash.split("?")[1]||"");const kwParam=params.get("q");if(kwParam&&kwEl)kwEl.value=kwParam;const kw=(kwEl?.value||"").toLowerCase().trim();const f=JOBS.filter(j=>!kw||(j.title+" "+j.company+" "+j.location+" "+j.tags.join(" ")).toLowerCase().includes(kw));$("#cnt").textContent=f.length+" results";$("#qe").textContent=kw?`for “${kw}”`:"";$("#results").innerHTML=f.map(jobCard).join("");$$("#results .act-detail").forEach(b=>b.addEventListener("click",e=>gotoJob(e.currentTarget.dataset.id)));$$("#results .act-save").forEach(b=>b.addEventListener("click",e=>toggleSave(e.currentTarget)));$$("#results .act-share").forEach(b=>b.addEventListener("click",e=>shareJob(e.currentTarget.dataset.id)));}
document.addEventListener("input",(e)=>{ if(e.target && e.target.id==="kw") loadJobs(); });

function gotoJob(id){ location.hash="/job?id="+id; }
function shareJob(id){ const url = location.origin + location.pathname + "#/job?id=" + id; if (navigator.share) navigator.share({title:"JobPortal",text:"Check this job",url}).catch(()=>{}); else { navigator.clipboard.writeText(url); alert("Link copied!"); } }
function toggleSave(btn){ const s = btn.dataset.saved === "1"; btn.dataset.saved = s ? "0":"1"; btn.textContent = s ? "Save":"Saved ✓"; }

function renderJobDetail(){ const params = new URLSearchParams(location.hash.split("?")[1] || ""); const id = params.get("id"); const j = JOBS.find(x=>String(x.id)===String(id)) || JOBS[0]; const posted = new Date(j.posted).toLocaleDateString();
  $("#jobContainer").innerHTML = `<div class="card"><div class="row spread vcenter"><div><h1 style="margin:.2rem 0">${j.title}</h1><div class="jobmeta"><span>${j.company}</span><span>${j.location}</span><span>${j.expMin}-${j.expMax} yrs</span><span>${j.ctc}</span></div><div class="tiny muted">Posted ${posted}</div></div><div class="row gap"><button class="btn ghost">Save</button><a class="btn primary" href="#/apply?id=${j.id}">Apply</a></div></div><p class="muted" style="margin-top:10px">${j.desc}</p><h3>Skills</h3><div style="margin-top:6px">${j.tags.map(t=>`<span class="tag">${t}</span>`).join("")}</div></div><div class="grid2" style="margin-top:12px"><div class="card"><h3>About Company</h3><p class="muted tiny">${j.company} is hiring for ${j.title}.</p></div><div class="card"><h3>Related Jobs</h3><div class="stack">${JOBS.filter(x=>x.id!==j.id).slice(0,3).map(job=>`<a class="btn ghost spread" href="#/job?id=${job.id}"><span>${job.title}</span><span>→</span></a>`).join("")}</div></div></div>`; }

function initResumes(){ const kw = ($("#rsKw")?.value||"").toLowerCase(); const f = JOBS.filter(j => !kw || (j.title+" "+j.tags.join(" ")).toLowerCase().includes(kw)); $("#rsCnt").textContent = f.length + " results"; $("#rsEcho").textContent = kw ? `for “${kw}”` : ""; $("#rsResults").innerHTML = f.map(j=>`<article class="jobcard"><div class="row spread"><div><div class="row gap vcenter"><h3 style="margin:.1rem 0">${j.title} candidate</h3><span class="badge">Top match</span></div><div class="jobmeta"><span>${j.location}</span><span>${j.expMin+1}-${j.expMax+1} yrs</span><span>${j.tags.slice(0,3).join(", ")}</span></div><div class="tiny muted">Updated Today</div></div><div class="jobactions"><button class="btn ghost" data-id="${j.id}" onclick="openPanel('${j.id}')">Preview</button><button class="btn ghost">Save</button><button class="btn ghost">Email</button></div></div></article>`).join(""); }
document.addEventListener("input",(e)=>{ if(e.target && e.target.id==="rsKw") initResumes(); });

function openPanel(id){ const j = JOBS.find(x=>String(x.id)===String(id)); $("#panelBody").innerHTML = `<h3>${j.title} — Candidate</h3><div class="tiny muted">${j.location} • ${j.expMin+1}-${j.expMax+1} yrs</div><h4>Summary</h4><p class="tiny">Hands-on with ${j.tags.join(", ")}. Strong collaboration and delivery.</p><h4>Experience</h4><ul class="tiny"><li>Company A — ${j.title} (2022–Present)</li><li>Company B — ${j.title} (2020–2022)</li></ul><div class="row gap mt"><button class="btn primary">Contact</button><button class="btn ghost">Download CV</button></div>`; $("#panel").classList.add("open"); }
document.addEventListener("click",(e)=>{ if (e.target && e.target.id==="panelClose") $("#panel").classList.remove("open"); });

function renderEmployerJobs(){ const kw = ($("#ejKw")?.value||"").toLowerCase(); const f = JOBS.filter(j => !kw || (j.title+" "+j.company).toLowerCase().includes(kw)); $("#ejResults").innerHTML = f.map(j=>`<article class="jobcard"><div class="row spread vcenter"><div><div class="row gap vcenter"><strong>${j.title}</strong><span class="badge">${j.company}</span></div><div class="tiny muted">${j.location} • ${j.expMin}-${j.expMax} yrs • ${j.ctc}</div></div><div class="row gap"><a class="btn ghost" href="#/job?id=${j.id}">View</a><button class="btn ghost">Responses (12)</button><button class="btn ghost">Close</button></div></div></article>`).join(""); }
document.addEventListener("input",(e)=>{ if(e.target && e.target.id==="ejKw") renderEmployerJobs(); });

const FLAGS = JSON.parse(localStorage.getItem("flags") || "[]");
function initAdmin(){ renderFlags(); document.addEventListener("click",(e)=>{ if(e.target && e.target.id==="flagAdd"){ const key = $("#flagKey").value.trim(); const enabled = $("#flagVal").checked; if(!key) return; const i = FLAGS.findIndex(f=>f.key===key); if(i>=0) FLAGS[i].enabled = enabled; else FLAGS.push({key,enabled}); localStorage.setItem("flags", JSON.stringify(FLAGS)); $("#flagKey").value=""; $("#flagVal").checked=false; renderFlags(); }});
  const input = $("#logoInput"); input?.addEventListener("change",(e)=>{ const f=e.target.files[0]; if(!f) return; const r=new FileReader(); r.onload=()=>{ localStorage.setItem("logoDataURL", r.result); document.querySelector(".brand img").src=r.result; alert("Logo updated (preview only)."); }; r.readAsDataURL(f); });
  const stored = localStorage.getItem("logoDataURL"); if(stored) document.querySelector(".brand img").src = stored; }
function renderFlags(){ $("#flags").innerHTML = FLAGS.length ? FLAGS.map(f=>`<div class="row spread vcenter" style="border:1px solid var(--border);border-radius:12px;padding:10px 12px"><div><div><strong>${f.key}</strong></div><div class="tiny muted">${f.enabled? "Enabled":"Disabled"}</div></div><span class="badge" style="background:${f.enabled?'#dcfce7':'#f1f5f9'};color:${f.enabled?'#166534':'#334155'}">${f.enabled? "ON":"OFF"}</span></div>`).join("") : `<div class="tiny muted">No flags yet. Add one below.</div>`; }
function bindGlobalSearch(){ $("#gbtn")?.addEventListener("click", ()=>{ const q = $("#gq").value.trim(); location.hash = "/jobs?q=" + encodeURIComponent(q); setTimeout(loadJobs, 50); }); }
